create or replace function public.c4_pattern_complement_alternative_shadow_v2(p_user_id uuid,p_session_id uuid,p_anchor_date date default current_date,p_session_context jsonb default '{}'::jsonb)
returns jsonb language plpgsql stable set search_path to 'public'
as $$
declare
  ws public.workout_sessions%rowtype; v_eval jsonb; v_inventory jsonb:='[]'::jsonb; v_stimulus jsonb:='{}'::jsonb; v_max_complexity int:=3; v_max_diff text:='Intermédiaire'; v_current_ids text[]:='{}'::text[]; v_current_patterns text[]:='{}'::text[];
  v_replace_id text; v_replace_pattern text; v_replace_position int; v_wod_count int:=0; v_wod_minutes int:=null; v_current_candidate jsonb; v_current_sim jsonb; v_current_fit numeric:=0; v_candidate record; v_profile jsonb; v_alt_exercises jsonb; v_alt_candidate jsonb; v_alt_sim jsonb; v_alt_fit numeric; v_best record; v_best_profile jsonb:=null; v_best_sim jsonb:=null; v_best_score_components jsonb:=null; v_best_candidate_score numeric:=null; v_best_fit numeric:=null; v_examined int:=0; v_feasible int:=0; v_projected_high_count int:=0; v_projected_status text; v_quality_delta numeric:=null; v_quality_interpretation text;
begin
  if auth.uid() is not null and auth.uid()<>p_user_id then raise exception 'Forbidden user'; end if;
  select * into ws from public.workout_sessions where id=p_session_id and user_id=p_user_id;
  if not found then return jsonb_build_object('version','pattern-complement-alternative-shadow-v2','mode','SHADOW','status','SESSION_NOT_FOUND'); end if;
  v_eval:=public.c4_pattern_complement_session_shadow_v1(p_user_id,p_session_id,coalesce(p_anchor_date,current_date),p_session_context);
  if coalesce(v_eval->>'status','')<>'SOFT_OVERLAP' then return jsonb_build_object('version','pattern-complement-alternative-shadow-v2','mode','SHADOW','status','NOT_NEEDED','reason','CURRENT_WOD_NOT_SOFT_OVERLAP','current_evaluation',v_eval,'authority',jsonb_build_object('shadow_only',true,'may_change_wod',false,'may_apply_replacement',false)); end if;
  v_inventory:=public.resolve_user_equipment_inventory(p_user_id,coalesce(ws.available_equipment,'{}'::text[]),'c4-final-default');
  v_stimulus:=case when coalesce(ws.expected_stimulus_json,'{}'::jsonb)<>'{}'::jsonb then ws.expected_stimulus_json else public.build_session_stimulus_target(coalesce(ws.focus,'General Fitness'),coalesce(ws.duration_minutes,45),coalesce(ws.readiness,'normal'),ws.target_region,ws.progression_intent,'c1-default') end;
  select greatest(1,coalesce(max(e.technical_complexity),3)),coalesce((array_agg(e.difficulty order by public.c4_difficulty_rank_v1(e.difficulty) desc,e.id))[1],'Intermédiaire'),coalesce(array_agg(wse.exercise_id order by wse.position),'{}'::text[]),coalesce(array_agg(e.movement_pattern order by wse.position),'{}'::text[]),count(*)::int into v_max_complexity,v_max_diff,v_current_ids,v_current_patterns,v_wod_count from public.workout_session_exercises wse join public.exercises e on e.id=wse.exercise_id where wse.session_id=p_session_id and wse.block_key='wod';
  select nullif(b->>'duration_minutes','')::int into v_wod_minutes from jsonb_array_elements(coalesce(ws.generated_workout->'blocks','[]'::jsonb)) b where b->>'block_key'='wod' limit 1;
  if v_wod_minutes is null then v_wod_minutes:=public.c3_wod_budget_minutes(coalesce(ws.duration_minutes,45),null,'c3-sim-default'); end if;
  with high_rows as (
    select (x->>'position')::int position,x->>'exercise_id' exercise_id,x->>'movement_pattern' movement_pattern,count(*) over(partition by x->>'movement_pattern') pattern_count,row_number() over(partition by x->>'movement_pattern' order by (x->>'position')::int) pattern_ordinal
    from jsonb_array_elements(coalesce(v_eval->'wod_pattern_ledger','[]'::jsonb)) x where coalesce((x->>'high_recent_pressure_unprotected')::boolean,false)
  ) select exercise_id,movement_pattern,position into v_replace_id,v_replace_pattern,v_replace_position from high_rows where pattern_count>=2 and pattern_ordinal>1 order by pattern_count desc,position desc limit 1;
  if v_replace_id is null then return jsonb_build_object('version','pattern-complement-alternative-shadow-v2','mode','SHADOW','status','NO_REPLACEMENT_TARGET','reason','SOFT_OVERLAP_WITHOUT_REPEATED_HIGH_PRESSURE_STATION','current_evaluation',v_eval,'authority',jsonb_build_object('shadow_only',true,'may_change_wod',false,'may_apply_replacement',false)); end if;
  select jsonb_build_object('mechanic',upper(coalesce(ws.mechanic_json->>'mechanic_key','CIRCUIT')),'exercises',coalesce(jsonb_agg(jsonb_build_object('exercise_id',wse.exercise_id,'prescription',case when coalesce(wse.prescription_json,'{}'::jsonb)<>'{}'::jsonb then wse.prescription_json else public.c2_solver_prescription(p_user_id,wse.exercise_id,v_stimulus,upper(coalesce(ws.mechanic_json->>'mechanic_key','CIRCUIT')),ws.progression_intent,v_inventory) end) order by wse.position),'[]'::jsonb)) into v_current_candidate from public.workout_session_exercises wse where wse.session_id=p_session_id and wse.block_key='wod';
  v_current_sim:=public.c3_simulate_candidate_wod(v_current_candidate,v_stimulus,coalesce(ws.duration_minutes,45),v_wod_minutes,'c3-sim-default'); v_current_fit:=coalesce(nullif(v_current_sim#>>'{whole_wod_metrics,whole_wod_fit}','')::numeric,0);
  for v_candidate in
    select cp.* from public.c2_candidate_pool_pattern_complement_shadow_v1(p_user_id,coalesce(ws.focus,'General Fitness'),coalesce(ws.duration_minutes,45),coalesce(ws.readiness,'normal'),ws.target_region,ws.progression_intent,coalesce(ws.injured_zones,'{}'::text[]),v_inventory,'WOD',v_max_complexity,v_max_diff,30,coalesce(p_anchor_date,current_date),p_session_context) cp
    where not(cp.exercise_id=any(v_current_ids)) and not(cp.movement_pattern=any(coalesce((select array_agg(value) from jsonb_array_elements_text(coalesce(v_eval#>'{policy,soft_avoid_patterns}','[]'::jsonb))),'{}'::text[])))
    order by case when cp.movement_pattern=any(v_current_patterns) then 1 else 0 end,cp.candidate_score desc,cp.exercise_id limit 15
  loop
    v_examined:=v_examined+1;
    v_profile:=public.c4_exercise_mechanic_profile(p_user_id,v_candidate.exercise_id,upper(coalesce(ws.mechanic_json->>'mechanic_key','CIRCUIT')),null,coalesce(ws.readiness,'normal'),ws.progression_intent);
    if not coalesce((v_profile->>'compatible')::boolean,false) or coalesce(v_profile->>'classification','') not in ('NATURAL','ADAPTABLE') then continue; end if;
    select coalesce(jsonb_agg(case when wse.position=v_replace_position then jsonb_build_object('exercise_id',v_candidate.exercise_id,'prescription',public.c2_solver_prescription(p_user_id,v_candidate.exercise_id,v_stimulus,upper(coalesce(ws.mechanic_json->>'mechanic_key','CIRCUIT')),ws.progression_intent,v_inventory)) else jsonb_build_object('exercise_id',wse.exercise_id,'prescription',case when coalesce(wse.prescription_json,'{}'::jsonb)<>'{}'::jsonb then wse.prescription_json else public.c2_solver_prescription(p_user_id,wse.exercise_id,v_stimulus,upper(coalesce(ws.mechanic_json->>'mechanic_key','CIRCUIT')),ws.progression_intent,v_inventory) end) end order by wse.position),'[]'::jsonb) into v_alt_exercises from public.workout_session_exercises wse where wse.session_id=p_session_id and wse.block_key='wod';
    v_alt_candidate:=jsonb_build_object('mechanic',upper(coalesce(ws.mechanic_json->>'mechanic_key','CIRCUIT')),'exercises',v_alt_exercises); v_alt_sim:=public.c3_simulate_candidate_wod(v_alt_candidate,v_stimulus,coalesce(ws.duration_minutes,45),v_wod_minutes,'c3-sim-default');
    if coalesce(v_alt_sim->>'status','')<>'OK' then continue; end if;
    v_feasible:=v_feasible+1; v_alt_fit:=coalesce(nullif(v_alt_sim#>>'{whole_wod_metrics,whole_wod_fit}','')::numeric,0);
    if v_best_fit is null or v_alt_fit>v_best_fit or (v_alt_fit=v_best_fit and v_candidate.candidate_score>coalesce(v_best_candidate_score,-999)) then
      select v_candidate.exercise_id exercise_id,v_candidate.exercise_name exercise_name,v_candidate.movement_pattern movement_pattern,v_candidate.exercise_family exercise_family into v_best;
      v_best_fit:=v_alt_fit; v_best_profile:=v_profile; v_best_sim:=v_alt_sim; v_best_score_components:=v_candidate.score_components; v_best_candidate_score:=v_candidate.candidate_score;
    end if;
  end loop;
  if v_best_fit is null then return jsonb_build_object('version','pattern-complement-alternative-shadow-v2','mode','SHADOW','status','NO_SAFE_COHERENT_ALTERNATIVE','reason','NO_C2_CANDIDATE_PRESERVES_CURRENT_MECHANIC_AND_C3_FEASIBILITY','replace_exercise_id',v_replace_id,'replace_pattern',v_replace_pattern,'replace_position',v_replace_position,'examined_candidates',v_examined,'c3_feasible_candidates',v_feasible,'current_evaluation',v_eval,'authority',jsonb_build_object('shadow_only',true,'may_change_wod',false,'may_apply_replacement',false)); end if;
  v_projected_high_count:=greatest(0,coalesce(nullif(v_eval->>'high_pressure_unprotected_count','')::int,0)-1); v_projected_status:=case when v_wod_count>0 and (v_projected_high_count>=2 or v_projected_high_count::numeric/v_wod_count>=0.40) then 'SOFT_OVERLAP' else 'COMPLEMENTED_OR_ACCEPTABLE' end; v_quality_delta:=round(v_best_fit-v_current_fit,2);
  v_quality_interpretation:=case when v_quality_delta>=0 then 'C3_QUALITY_IMPROVED' when v_quality_delta>=-2 then 'C3_QUALITY_NEAR_EQUIVALENT' when v_quality_delta>=-5 then 'C3_QUALITY_SMALL_TRADEOFF' else 'C3_QUALITY_MATERIAL_TRADEOFF' end;
  return jsonb_build_object('version','pattern-complement-alternative-shadow-v2','mode','SHADOW','status','ALTERNATIVE_PROPOSED','reason','BEST_C3_FEASIBLE_COMPLEMENTARY_CANDIDATE_SELECTED','replace',jsonb_build_object('position',v_replace_position,'exercise_id',v_replace_id,'movement_pattern',v_replace_pattern),'with',jsonb_build_object('exercise_id',v_best.exercise_id,'name',v_best.exercise_name,'movement_pattern',v_best.movement_pattern,'exercise_family',v_best.exercise_family,'candidate_score',v_best_candidate_score,'score_components',v_best_score_components,'mechanic_profile',v_best_profile),'quality_comparison',jsonb_build_object('wod_budget_minutes',v_wod_minutes,'current_whole_wod_fit',round(v_current_fit,2),'alternative_whole_wod_fit',round(v_best_fit,2),'delta',v_quality_delta,'interpretation',v_quality_interpretation,'current_metrics',v_current_sim->'whole_wod_metrics','alternative_metrics',v_best_sim->'whole_wod_metrics'),'current_evaluation',v_eval,'examined_candidates',v_examined,'c3_feasible_candidates',v_feasible,'projected_high_pressure_unprotected_count',v_projected_high_count,'projected_pattern_status',v_projected_status,'same_wod_mechanic',upper(coalesce(ws.mechanic_json->>'mechanic_key','CIRCUIT')),'hard_gates_reused_from_c2',true,'whole_wod_quality_rechecked_with_c3',true,'authority',jsonb_build_object('shadow_only',true,'may_change_wod',false,'may_apply_replacement',false,'c4_remains_authoritative',true));
end;
$$;
revoke all on function public.c4_pattern_complement_alternative_shadow_v2(uuid,uuid,date,jsonb) from public,anon;
grant execute on function public.c4_pattern_complement_alternative_shadow_v2(uuid,uuid,date,jsonb) to authenticated,service_role;

create or replace function public.program_coach_mechanic_policy_session_shadow_v1(p_user_id uuid,p_session_id uuid,p_session_context jsonb default '{}'::jsonb)
returns jsonb language plpgsql stable set search_path to 'public'
as $$
declare ws record; v_intent text; v_stimulus jsonb; v_rank jsonb; v_current text; v_proposed text; v_apply boolean:=false; v_pattern_complement jsonb:='{}'::jsonb; v_pattern_alternative jsonb:='{}'::jsonb; v_anchor date:=current_date;
begin
  if auth.uid() is not null and auth.uid()<>p_user_id then raise exception 'Forbidden user'; end if;
  select id,focus,duration_minutes,readiness,target_region,progression_intent,expected_stimulus_json,mechanic_json,planning_context_json,generation_local_date into ws from public.workout_sessions where id=p_session_id and user_id=p_user_id;
  if not found then return jsonb_build_object('version','mechanic-policy-session-shadow-v1','mode','SHADOW','status','SESSION_NOT_FOUND'); end if;
  select coalesce((config#>>'{mechanic_policy,apply_enabled}')::boolean,false) into v_apply from public.session_engine_policy where policy_key='c4-final-default';
  v_intent:=coalesce(nullif(p_session_context#>>'{session_intent_shadow,proposed_session_intent}',''),nullif(ws.planning_context_json#>>'{weekly_loop,session_intent_shadow,proposed_session_intent}',''),public.program_coach_solver_session_intent_v1(p_user_id,coalesce(ws.focus,'General Fitness'),coalesce(ws.duration_minutes,45),coalesce(ws.readiness,'normal'),ws.progression_intent)->>'proposed_session_intent','CLASSIC');
  v_stimulus:=coalesce(ws.expected_stimulus_json,public.build_session_stimulus_target(coalesce(ws.focus,'General Fitness'),coalesce(ws.duration_minutes,45),coalesce(ws.readiness,'normal'),ws.target_region,ws.progression_intent,'c1-default'))||jsonb_build_object('session_intent_shadow',v_intent,'mechanic_policy_shadow_version','mechanic-policy-shadow-v1');
  v_rank:=public.program_coach_mechanic_policy_rank_v1(v_stimulus,ws.progression_intent); v_current:=upper(coalesce(ws.mechanic_json->>'mechanic_key',ws.mechanic_json->>'mechanic','')); v_proposed:=upper(coalesce(v_rank#>>'{ranked_mechanics,0,mechanic}','')); v_anchor:=coalesce(ws.generation_local_date,current_date);
  begin v_pattern_complement:=public.c4_pattern_complement_session_shadow_v1(p_user_id,p_session_id,v_anchor,p_session_context); v_pattern_alternative:=public.c4_pattern_complement_alternative_shadow_v2(p_user_id,p_session_id,v_anchor,p_session_context); exception when others then v_pattern_complement:=jsonb_build_object('version','pattern-complement-session-shadow-v1','mode','SHADOW','status','UNAVAILABLE','reason','SHADOW_EVALUATION_ERROR','error',sqlerrm,'authority',jsonb_build_object('shadow_only',true,'may_change_wod',false)); v_pattern_alternative:=jsonb_build_object('version','pattern-complement-alternative-shadow-v2','mode','SHADOW','status','UNAVAILABLE','reason','SHADOW_EVALUATION_ERROR','error',sqlerrm,'authority',jsonb_build_object('shadow_only',true,'may_change_wod',false)); end;
  return jsonb_build_object('version','mechanic-policy-session-shadow-v1','mode','SHADOW','status','PROPOSED','session_id',p_session_id,'session_intent',v_intent,'current_authoritative_mechanic',nullif(v_current,''),'proposed_top_mechanic',nullif(v_proposed,''),'would_differ_from_current',v_current<>v_proposed and v_current<>'' and v_proposed<>'','ranked_mechanics',coalesce(v_rank->'ranked_mechanics','[]'::jsonb),'candidate_selection_mode','authoritative_top3_plus_policy_top3_then_c4','apply_enabled',v_apply,'pattern_complement_shadow',v_pattern_complement,'pattern_complement_alternative_shadow',v_pattern_alternative,'authority',jsonb_build_object('shadow_only',true,'may_change_session_decision',false,'may_change_mechanic',false,'c4_remains_authoritative',true));
end;
$$;