create table if not exists public.weekly_loop_run_errors (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  session_id uuid references public.workout_sessions(id) on delete cascade,
  error_text text not null,
  created_at timestamptz not null default now()
);
alter table public.weekly_loop_run_errors enable row level security;
drop policy if exists "Users read own weekly loop errors" on public.weekly_loop_run_errors;
create policy "Users read own weekly loop errors" on public.weekly_loop_run_errors for select using (auth.uid()=user_id);
;
