-- Engine policy tables: never client-writable.
alter table public.session_engine_policy enable row level security;
drop policy if exists "Authenticated can read session engine policy" on public.session_engine_policy;
create policy "Authenticated can read session engine policy"
on public.session_engine_policy for select to authenticated using (true);

revoke all on table public.session_engine_policy from anon;
revoke insert, update, delete, truncate, references, trigger on table public.session_engine_policy from authenticated;
grant select on table public.session_engine_policy to authenticated;

revoke all on table public.performance_engine_policy from anon;
revoke insert, update, delete, truncate, references, trigger on table public.performance_engine_policy from authenticated;
grant select on table public.performance_engine_policy to authenticated;

revoke all on table public.performance_observation_quality_policy from anon;
revoke insert, update, delete, truncate, references, trigger on table public.performance_observation_quality_policy from authenticated;
grant select on table public.performance_observation_quality_policy to authenticated;

-- Engine event ledgers: user may inspect own history, never forge it.
revoke all on table public.capability_update_events from anon;
revoke insert, update, delete, truncate, references, trigger on table public.capability_update_events from authenticated;
grant select on table public.capability_update_events to authenticated;

revoke all on table public.protocol_capability_events from anon;
revoke insert, update, delete, truncate, references, trigger on table public.protocol_capability_events from authenticated;
grant select on table public.protocol_capability_events to authenticated;

revoke all on table public.capability_shadow_events from anon;
revoke insert, update, delete, truncate, references, trigger on table public.capability_shadow_events from authenticated;
grant select on table public.capability_shadow_events to authenticated;

revoke all on table public.capability_shadow_run_errors from anon;
revoke insert, update, delete, truncate, references, trigger on table public.capability_shadow_run_errors from authenticated;
grant select on table public.capability_shadow_run_errors to authenticated;

-- Live exercise capability is derived state, not user-editable state.
drop policy if exists "Users can insert own exercise capabilities" on public.user_exercise_capabilities;
drop policy if exists "Users can update own exercise capabilities" on public.user_exercise_capabilities;
drop policy if exists "Users can delete own exercise capabilities" on public.user_exercise_capabilities;
drop policy if exists "Users can read own exercise capabilities" on public.user_exercise_capabilities;
create policy "Users can read own exercise capabilities"
on public.user_exercise_capabilities for select to authenticated
using (auth.uid() = user_id);
revoke all on table public.user_exercise_capabilities from anon;
revoke insert, update, delete, truncate, references, trigger on table public.user_exercise_capabilities from authenticated;
grant select on table public.user_exercise_capabilities to authenticated;

-- Work-rate estimates are derived by the secured trigger.
revoke all on table public.user_exercise_work_rate_estimates from anon;
revoke insert, update, delete, truncate, references, trigger on table public.user_exercise_work_rate_estimates from authenticated;
grant select on table public.user_exercise_work_rate_estimates to authenticated;

-- Protocol capability is also computed by the coach.
drop policy if exists "user_protocol_capabilities_own_all" on public.user_protocol_capabilities;
create policy "user_protocol_capabilities_select_own"
on public.user_protocol_capabilities for select to authenticated
using (user_id = auth.uid());
revoke all on table public.user_protocol_capabilities from anon;
revoke insert, update, delete, truncate, references, trigger on table public.user_protocol_capabilities from authenticated;
grant select on table public.user_protocol_capabilities to authenticated;

-- Weekly adaptive state is generated by D, not authored by the mobile client.
drop policy if exists "Users own training weeks" on public.user_training_weeks;
create policy "Users read own training weeks"
on public.user_training_weeks for select to authenticated using (auth.uid() = user_id);
revoke all on table public.user_training_weeks from anon;
revoke insert, update, delete, truncate, references, trigger on table public.user_training_weeks from authenticated;
grant select on table public.user_training_weeks to authenticated;

drop policy if exists "Users own training plan items" on public.user_training_plan_items;
create policy "Users read own training plan items"
on public.user_training_plan_items for select to authenticated using (auth.uid() = user_id);
revoke all on table public.user_training_plan_items from anon;
revoke insert, update, delete, truncate, references, trigger on table public.user_training_plan_items from authenticated;
grant select on table public.user_training_plan_items to authenticated;

drop policy if exists "Users own weekly stimulus targets" on public.weekly_stimulus_targets;
create policy "Users read own weekly stimulus targets"
on public.weekly_stimulus_targets for select to authenticated using (auth.uid() = user_id);
revoke all on table public.weekly_stimulus_targets from anon;
revoke insert, update, delete, truncate, references, trigger on table public.weekly_stimulus_targets from authenticated;
grant select on table public.weekly_stimulus_targets to authenticated;

drop policy if exists "Users own session stimulus ledger" on public.session_stimulus_ledger;
create policy "Users read own session stimulus ledger"
on public.session_stimulus_ledger for select to authenticated using (auth.uid() = user_id);
revoke all on table public.session_stimulus_ledger from anon;
revoke insert, update, delete, truncate, references, trigger on table public.session_stimulus_ledger from authenticated;
grant select on table public.session_stimulus_ledger to authenticated;;
