-- B2.5 — capability update engine foundations.
-- The proposal function is pure: it never writes user capability state.

ALTER TABLE public.user_exercise_capabilities
  ADD COLUMN IF NOT EXISTS progressive_envelope jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS engine_version text NOT NULL DEFAULT 'b2.5-draft-1';

ALTER TABLE public.user_exercise_capabilities
  DROP CONSTRAINT IF EXISTS user_exercise_capabilities_progressive_object_check;
ALTER TABLE public.user_exercise_capabilities
  ADD CONSTRAINT user_exercise_capabilities_progressive_object_check
  CHECK (jsonb_typeof(progressive_envelope)='object');

CREATE TABLE IF NOT EXISTS public.capability_update_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  exercise_id varchar NOT NULL REFERENCES public.exercises(id) ON DELETE CASCADE,
  exercise_log_id bigint REFERENCES public.exercise_logs(id) ON DELETE SET NULL,
  capability_family text NOT NULL,
  engine_version text NOT NULL,
  decision text NOT NULL,
  reason_codes text[] NOT NULL DEFAULT '{}'::text[],
  observation_role text,
  quality_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  comparison_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  before_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  proposal_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  after_json jsonb,
  applied boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  applied_at timestamptz,
  CONSTRAINT capability_update_events_family_check CHECK (
    capability_family IN ('reps','load_reps','time','pace','loaded_distance','density','progressive')
  ),
  CONSTRAINT capability_update_events_decision_check CHECK (
    decision IN ('EXCLUDE','CONFIRM','EXPAND','ADD_FRONTIER_POINT','HOLD','RECALIBRATE','REGRESS_CONFIRMED')
  ),
  CONSTRAINT capability_update_events_json_check CHECK (
    jsonb_typeof(quality_json)='object' AND
    jsonb_typeof(comparison_json)='object' AND
    jsonb_typeof(before_json)='object' AND
    jsonb_typeof(proposal_json)='object' AND
    (after_json IS NULL OR jsonb_typeof(after_json)='object')
  ),
  CONSTRAINT capability_update_events_applied_check CHECK (
    (NOT applied AND applied_at IS NULL) OR (applied AND applied_at IS NOT NULL AND after_json IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_capability_update_events_user_exercise_time
  ON public.capability_update_events(user_id,exercise_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_capability_update_events_log
  ON public.capability_update_events(exercise_log_id);

ALTER TABLE public.capability_update_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can read own capability update events" ON public.capability_update_events;
CREATE POLICY "Users can read own capability update events"
  ON public.capability_update_events FOR SELECT TO authenticated
  USING (auth.uid()=user_id);

-- Utility: extract a numeric JSON value safely.
CREATE OR REPLACE FUNCTION public.jsonb_num(p_doc jsonb, p_key text)
RETURNS numeric
LANGUAGE sql IMMUTABLE AS $$
  SELECT CASE
    WHEN p_doc ? p_key AND jsonb_typeof(p_doc->p_key)='number' THEN (p_doc->>p_key)::numeric
    ELSE NULL
  END;
$$;

-- Utility: clamp numeric.
CREATE OR REPLACE FUNCTION public.num_clamp(p_value numeric,p_min numeric,p_max numeric)
RETURNS numeric
LANGUAGE sql IMMUTABLE AS $$
  SELECT LEAST(p_max,GREATEST(p_min,p_value));
$$;

-- Pure proposal engine. No DB write.
-- Input current envelope is family-specific JSON. Observation must already be classified by B2.4.
CREATE OR REPLACE FUNCTION public.propose_capability_update(
  p_family text,
  p_current jsonb,
  p_expected jsonb,
  p_actual jsonb,
  p_quality numeric,
  p_confirmed boolean,
  p_capability_eligible boolean,
  p_pain_affected boolean,
  p_observed_at timestamptz DEFAULT now()
) RETURNS jsonb
LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE
  v_current jsonb := COALESCE(p_current,'{}'::jsonb);
  v_quality numeric := public.num_clamp(COALESCE(p_quality,0),0,1);
  v_expected_rpe numeric := COALESCE(public.jsonb_num(p_expected,'target_rpe'),public.jsonb_num(p_expected,'target_rpe_max'));
  v_actual_rpe numeric := public.jsonb_num(p_actual,'rpe');
  v_rpe_delta numeric := CASE WHEN v_expected_rpe IS NOT NULL AND v_actual_rpe IS NOT NULL THEN v_actual_rpe-v_expected_rpe ELSE 0 END;
  v_result jsonb;
  v_reason text[] := '{}'::text[];
  v_decision text := 'HOLD';
  v_signal text := 'NEUTRAL';
  v_expected_value numeric;
  v_actual_value numeric;
  v_old_value numeric;
  v_load numeric;
  v_reps numeric;
  v_frontier jsonb;
  v_point jsonb;
  v_stage numeric;
  v_partial numeric;
BEGIN
  IF p_family NOT IN ('reps','load_reps','time','pace','loaded_distance','density','progressive') THEN
    RAISE EXCEPTION 'Unsupported capability family: %',p_family;
  END IF;

  IF NOT COALESCE(p_capability_eligible,false) OR COALESCE(p_pain_affected,false) THEN
    v_decision := 'EXCLUDE';
    v_reason := CASE WHEN COALESCE(p_pain_affected,false)
      THEN ARRAY['PAIN_STATE_ONLY']::text[] ELSE ARRAY['NOT_CAPABILITY_ELIGIBLE']::text[] END;
    RETURN jsonb_build_object(
      'engine_version','b2.5-draft-1','family',p_family,'decision',v_decision,
      'signal','NONE','reason_codes',v_reason,'before',v_current,'after',v_current,
      'quality',v_quality,'confirmed',COALESCE(p_confirmed,false),'observed_at',p_observed_at
    );
  END IF;

  IF v_quality <= 0 THEN
    RETURN jsonb_build_object(
      'engine_version','b2.5-draft-1','family',p_family,'decision','HOLD',
      'signal','NONE','reason_codes',ARRAY['ZERO_QUALITY']::text[],'before',v_current,'after',v_current,
      'quality',v_quality,'confirmed',COALESCE(p_confirmed,false),'observed_at',p_observed_at
    );
  END IF;

  IF p_family='reps' THEN
    v_expected_value := COALESCE(public.jsonb_num(p_expected,'reps_target'),public.jsonb_num(p_expected,'reps_max'),public.jsonb_num(p_expected,'reps_min'));
    v_actual_value := public.jsonb_num(p_actual,'reps');
    v_old_value := public.jsonb_num(v_current,'repeatable_reps');
    IF v_actual_value IS NULL THEN
      v_reason := ARRAY['MISSING_REPS'];
    ELSIF v_old_value IS NULL THEN
      v_decision := 'CONFIRM'; v_signal := 'INITIALIZE';
      v_current := v_current || jsonb_build_object('repeatable_reps',v_actual_value,'last_observed_at',p_observed_at);
      v_reason := ARRAY['FIRST_VALID_REPS'];
    ELSIF v_actual_value > v_old_value AND v_rpe_delta <= 0 THEN
      v_decision := CASE WHEN p_confirmed THEN 'EXPAND' ELSE 'HOLD' END;
      v_signal := 'POSITIVE';
      IF p_confirmed THEN v_current := v_current || jsonb_build_object('repeatable_reps',v_actual_value,'last_observed_at',p_observed_at); END IF;
      v_reason := CASE WHEN p_confirmed THEN ARRAY['HIGHER_REPS_CONFIRMED'] ELSE ARRAY['HIGHER_REPS_UNCONFIRMED'] END;
    ELSIF v_actual_value = v_old_value AND v_rpe_delta < 0 THEN
      v_decision := 'CONFIRM'; v_signal := 'POSITIVE_EFFICIENCY';
      v_reason := ARRAY['SAME_REPS_LOWER_RPE'];
    ELSIF v_actual_value < v_old_value AND v_rpe_delta > 0 THEN
      v_signal := 'NEGATIVE';
      IF p_confirmed THEN
        v_decision := 'REGRESS_CONFIRMED';
        v_current := v_current || jsonb_build_object('repeatable_reps',v_actual_value,'last_observed_at',p_observed_at);
        v_reason := ARRAY['LOWER_REPS_HIGHER_RPE_CONFIRMED'];
      ELSE
        v_decision := 'HOLD'; v_reason := ARRAY['NEGATIVE_UNCONFIRMED_STATE_ONLY'];
      END IF;
    ELSE
      v_decision := 'CONFIRM'; v_reason := ARRAY['REPS_COMPATIBLE_WITH_ENVELOPE'];
    END IF;

  ELSIF p_family='time' THEN
    v_actual_value := public.jsonb_num(p_actual,'duration_seconds');
    v_old_value := public.jsonb_num(v_current,'repeatable_seconds');
    IF v_actual_value IS NULL THEN
      v_reason := ARRAY['MISSING_DURATION'];
    ELSIF v_old_value IS NULL THEN
      v_decision := 'CONFIRM'; v_signal := 'INITIALIZE';
      v_current := v_current || jsonb_build_object('repeatable_seconds',v_actual_value,'last_observed_at',p_observed_at);
      v_reason := ARRAY['FIRST_VALID_TIME'];
    ELSIF v_actual_value > v_old_value AND v_rpe_delta <= 0 THEN
      v_signal := 'POSITIVE';
      IF p_confirmed THEN v_decision := 'EXPAND'; v_current := v_current || jsonb_build_object('repeatable_seconds',v_actual_value,'last_observed_at',p_observed_at); v_reason:=ARRAY['LONGER_HOLD_CONFIRMED'];
      ELSE v_decision := 'HOLD'; v_reason:=ARRAY['LONGER_HOLD_UNCONFIRMED']; END IF;
    ELSIF v_actual_value < v_old_value AND v_rpe_delta > 0 THEN
      v_signal := 'NEGATIVE';
      IF p_confirmed THEN v_decision := 'REGRESS_CONFIRMED'; v_current := v_current || jsonb_build_object('repeatable_seconds',v_actual_value,'last_observed_at',p_observed_at); v_reason:=ARRAY['SHORTER_HOLD_HIGHER_RPE_CONFIRMED'];
      ELSE v_decision := 'HOLD'; v_reason:=ARRAY['NEGATIVE_UNCONFIRMED_STATE_ONLY']; END IF;
    ELSE
      v_decision := 'CONFIRM'; v_reason:=ARRAY['TIME_COMPATIBLE_WITH_ENVELOPE'];
    END IF;

  ELSIF p_family='load_reps' THEN
    v_load := public.jsonb_num(p_actual,'load_kg');
    v_reps := public.jsonb_num(p_actual,'reps');
    IF v_load IS NULL OR v_reps IS NULL THEN
      v_reason := ARRAY['MISSING_LOAD_OR_REPS'];
    ELSE
      v_frontier := COALESCE(v_current->'frontier','[]'::jsonb);
      IF jsonb_typeof(v_frontier) <> 'array' THEN v_frontier := '[]'::jsonb; END IF;
      v_point := jsonb_build_object('load_kg',v_load,'reps',v_reps,'rpe',v_actual_rpe,'quality',v_quality,'observed_at',p_observed_at);
      -- Keep a Pareto frontier: remove points dominated by the new point.
      IF EXISTS (
        SELECT 1 FROM jsonb_array_elements(v_frontier) x
        WHERE public.jsonb_num(x,'load_kg') >= v_load AND public.jsonb_num(x,'reps') >= v_reps
          AND (public.jsonb_num(x,'load_kg') > v_load OR public.jsonb_num(x,'reps') > v_reps)
      ) THEN
        v_signal := 'BELOW_FRONTIER';
        IF p_confirmed AND v_rpe_delta > 0 THEN v_decision:='REGRESS_CONFIRMED'; v_reason:=ARRAY['BELOW_FRONTIER_CONFIRMED'];
        ELSE v_decision:='HOLD'; v_reason:=ARRAY['BELOW_FRONTIER_NOT_ENOUGH_TO_REGRESS']; END IF;
      ELSE
        SELECT COALESCE(jsonb_agg(x),'[]'::jsonb) INTO v_frontier
        FROM jsonb_array_elements(v_frontier) x
        WHERE NOT (
          public.jsonb_num(x,'load_kg') <= v_load AND public.jsonb_num(x,'reps') <= v_reps
          AND (public.jsonb_num(x,'load_kg') < v_load OR public.jsonb_num(x,'reps') < v_reps)
        );
        v_frontier := v_frontier || jsonb_build_array(v_point);
        v_current := v_current || jsonb_build_object('frontier',v_frontier,'last_observed_at',p_observed_at);
        v_decision := 'ADD_FRONTIER_POINT'; v_signal := 'POSITIVE_OR_NEW_CAPACITY_POINT';
        v_reason := ARRAY['NON_DOMINATED_LOAD_REP_POINT'];
      END IF;
    END IF;

  ELSIF p_family='pace' THEN
    IF public.jsonb_num(p_actual,'distance_meters') IS NOT NULL AND public.jsonb_num(p_actual,'duration_seconds') IS NOT NULL AND public.jsonb_num(p_actual,'duration_seconds') > 0 THEN
      v_actual_value := public.jsonb_num(p_actual,'distance_meters') / public.jsonb_num(p_actual,'duration_seconds');
    END IF;
    v_old_value := public.jsonb_num(v_current,'repeatable_mps');
    IF v_actual_value IS NULL THEN v_reason:=ARRAY['MISSING_DISTANCE_OR_TIME'];
    ELSIF v_old_value IS NULL THEN v_decision:='CONFIRM'; v_signal:='INITIALIZE'; v_current:=v_current||jsonb_build_object('repeatable_mps',v_actual_value,'last_observed_at',p_observed_at); v_reason:=ARRAY['FIRST_VALID_PACE'];
    ELSIF v_actual_value > v_old_value AND v_rpe_delta <= 0 THEN v_signal:='POSITIVE'; IF p_confirmed THEN v_decision:='EXPAND'; v_current:=v_current||jsonb_build_object('repeatable_mps',v_actual_value,'last_observed_at',p_observed_at); v_reason:=ARRAY['FASTER_PACE_CONFIRMED']; ELSE v_decision:='HOLD'; v_reason:=ARRAY['FASTER_PACE_UNCONFIRMED']; END IF;
    ELSIF v_actual_value < v_old_value AND v_rpe_delta > 0 THEN v_signal:='NEGATIVE'; IF p_confirmed THEN v_decision:='REGRESS_CONFIRMED'; v_current:=v_current||jsonb_build_object('repeatable_mps',v_actual_value,'last_observed_at',p_observed_at); v_reason:=ARRAY['SLOWER_PACE_HIGHER_RPE_CONFIRMED']; ELSE v_decision:='HOLD'; v_reason:=ARRAY['NEGATIVE_UNCONFIRMED_STATE_ONLY']; END IF;
    ELSE v_decision:='CONFIRM'; v_reason:=ARRAY['PACE_COMPATIBLE_WITH_ENVELOPE']; END IF;

  ELSIF p_family='loaded_distance' THEN
    v_load := public.jsonb_num(p_actual,'load_kg');
    IF public.jsonb_num(p_actual,'distance_meters') IS NOT NULL AND public.jsonb_num(p_actual,'duration_seconds') IS NOT NULL AND public.jsonb_num(p_actual,'duration_seconds') > 0 THEN
      v_actual_value := public.jsonb_num(p_actual,'distance_meters') / public.jsonb_num(p_actual,'duration_seconds');
    END IF;
    IF v_load IS NULL OR v_actual_value IS NULL THEN v_reason:=ARRAY['MISSING_LOAD_DISTANCE_OR_TIME'];
    ELSE
      v_frontier := COALESCE(v_current->'frontier','[]'::jsonb); IF jsonb_typeof(v_frontier)<>'array' THEN v_frontier:='[]'::jsonb; END IF;
      v_point:=jsonb_build_object('load_kg',v_load,'distance_meters',public.jsonb_num(p_actual,'distance_meters'),'duration_seconds',public.jsonb_num(p_actual,'duration_seconds'),'pace_mps',v_actual_value,'rpe',v_actual_rpe,'quality',v_quality,'observed_at',p_observed_at);
      -- For carries, do not scalarize load and pace. Keep non-dominated observations.
      IF EXISTS (SELECT 1 FROM jsonb_array_elements(v_frontier) x WHERE public.jsonb_num(x,'load_kg')>=v_load AND public.jsonb_num(x,'pace_mps')>=v_actual_value AND (public.jsonb_num(x,'load_kg')>v_load OR public.jsonb_num(x,'pace_mps')>v_actual_value)) THEN
        v_decision:='HOLD'; v_signal:='BELOW_FRONTIER'; v_reason:=ARRAY['LOADED_DISTANCE_BELOW_FRONTIER'];
      ELSE
        SELECT COALESCE(jsonb_agg(x),'[]'::jsonb) INTO v_frontier FROM jsonb_array_elements(v_frontier) x
        WHERE NOT (public.jsonb_num(x,'load_kg')<=v_load AND public.jsonb_num(x,'pace_mps')<=v_actual_value AND (public.jsonb_num(x,'load_kg')<v_load OR public.jsonb_num(x,'pace_mps')<v_actual_value));
        v_frontier:=v_frontier||jsonb_build_array(v_point); v_current:=v_current||jsonb_build_object('frontier',v_frontier,'last_observed_at',p_observed_at);
        v_decision:='ADD_FRONTIER_POINT'; v_signal:='POSITIVE_OR_NEW_CAPACITY_POINT'; v_reason:=ARRAY['NON_DOMINATED_LOADED_DISTANCE_POINT'];
      END IF;
    END IF;

  ELSIF p_family='progressive' THEN
    v_stage := public.jsonb_num(p_actual,'last_completed_stage');
    v_partial := COALESCE(public.jsonb_num(p_actual,'partial_next_stage'),0);
    v_actual_value := CASE WHEN v_stage IS NULL THEN NULL ELSE v_stage + public.num_clamp(v_partial,0,0.999) END;
    v_old_value := public.jsonb_num(v_current,'threshold_stage_equivalent');
    IF v_actual_value IS NULL THEN v_reason:=ARRAY['MISSING_PROGRESSIVE_STAGE'];
    ELSIF v_old_value IS NULL THEN v_decision:='CONFIRM'; v_signal:='INITIALIZE'; v_current:=v_current||jsonb_build_object('threshold_stage_equivalent',v_actual_value,'last_completed_stage',v_stage,'partial_next_stage',v_partial,'last_observed_at',p_observed_at); v_reason:=ARRAY['FIRST_VALID_PROGRESSIVE_THRESHOLD'];
    ELSIF v_actual_value > v_old_value THEN v_signal:='POSITIVE'; IF p_confirmed THEN v_decision:='EXPAND'; v_current:=v_current||jsonb_build_object('threshold_stage_equivalent',v_actual_value,'last_completed_stage',v_stage,'partial_next_stage',v_partial,'last_observed_at',p_observed_at); v_reason:=ARRAY['HIGHER_PROGRESSIVE_THRESHOLD_CONFIRMED']; ELSE v_decision:='HOLD'; v_reason:=ARRAY['HIGHER_PROGRESSIVE_THRESHOLD_UNCONFIRMED']; END IF;
    ELSIF v_actual_value < v_old_value THEN v_signal:='NEGATIVE'; IF p_confirmed THEN v_decision:='REGRESS_CONFIRMED'; v_current:=v_current||jsonb_build_object('threshold_stage_equivalent',v_actual_value,'last_completed_stage',v_stage,'partial_next_stage',v_partial,'last_observed_at',p_observed_at); v_reason:=ARRAY['LOWER_PROGRESSIVE_THRESHOLD_CONFIRMED']; ELSE v_decision:='HOLD'; v_reason:=ARRAY['NEGATIVE_UNCONFIRMED_STATE_ONLY']; END IF;
    ELSE v_decision:='CONFIRM'; v_reason:=ARRAY['PROGRESSIVE_THRESHOLD_CONFIRMED']; END IF;

  ELSE -- density
    v_expected_value := public.jsonb_num(p_actual,'density_value');
    v_old_value := public.jsonb_num(v_current,'repeatable_density');
    IF v_expected_value IS NULL THEN v_reason:=ARRAY['MISSING_DENSITY_VALUE'];
    ELSIF v_old_value IS NULL THEN v_decision:='CONFIRM'; v_signal:='INITIALIZE'; v_current:=v_current||jsonb_build_object('repeatable_density',v_expected_value,'last_observed_at',p_observed_at); v_reason:=ARRAY['FIRST_VALID_DENSITY'];
    ELSIF v_expected_value > v_old_value AND v_rpe_delta<=0 THEN v_signal:='POSITIVE'; IF p_confirmed THEN v_decision:='EXPAND'; v_current:=v_current||jsonb_build_object('repeatable_density',v_expected_value,'last_observed_at',p_observed_at); v_reason:=ARRAY['HIGHER_DENSITY_CONFIRMED']; ELSE v_decision:='HOLD'; v_reason:=ARRAY['HIGHER_DENSITY_UNCONFIRMED']; END IF;
    ELSIF v_expected_value < v_old_value AND v_rpe_delta>0 THEN v_signal:='NEGATIVE'; IF p_confirmed THEN v_decision:='REGRESS_CONFIRMED'; v_current:=v_current||jsonb_build_object('repeatable_density',v_expected_value,'last_observed_at',p_observed_at); v_reason:=ARRAY['LOWER_DENSITY_CONFIRMED']; ELSE v_decision:='HOLD'; v_reason:=ARRAY['NEGATIVE_UNCONFIRMED_STATE_ONLY']; END IF;
    ELSE v_decision:='CONFIRM'; v_reason:=ARRAY['DENSITY_COMPATIBLE_WITH_ENVELOPE']; END IF;
  END IF;

  v_result := jsonb_build_object(
    'engine_version','b2.5-draft-1','family',p_family,'decision',v_decision,'signal',v_signal,
    'reason_codes',v_reason,'before',COALESCE(p_current,'{}'::jsonb),'after',v_current,
    'quality',v_quality,'confirmed',COALESCE(p_confirmed,false),'rpe_delta',v_rpe_delta,
    'observed_at',p_observed_at
  );
  RETURN v_result;
END;
$$;;
