create table if not exists public.user_exercise_capabilities_shadow (
  user_id uuid not null references auth.users(id) on delete cascade,
  exercise_id varchar not null references public.exercises(id) on delete cascade,
  state_json jsonb not null default '{}'::jsonb,
  engine_policy_key text not null default 'b2.5-draft-default',
  quality_policy_key text not null default 'b2.6-adapter-draft-1',
  last_observed_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key(user_id,exercise_id),
  check (jsonb_typeof(state_json)='object')
);

create table if not exists public.capability_shadow_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid references public.workout_sessions(id) on delete cascade,
  exercise_log_id bigint not null references public.exercise_logs(id) on delete cascade,
  session_exercise_id uuid references public.workout_session_exercises(id) on delete set null,
  exercise_id varchar not null references public.exercises(id) on delete cascade,
  capability_family text not null,
  capability_mode text not null,
  decision text not null,
  signal text not null,
  confirmed_now boolean not null default false,
  quality numeric(6,4) not null,
  effective_evidence numeric(10,4),
  confidence numeric(10,4),
  reason_codes text[] not null default '{}'::text[],
  comparison_json jsonb not null default '{}'::jsonb,
  result_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check (capability_mode in ('fresh','repeatable')),
  check (quality between 0 and 1),
  unique(exercise_log_id,capability_family,capability_mode)
);

create table if not exists public.capability_shadow_run_errors (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  session_id uuid references public.workout_sessions(id) on delete cascade,
  error_text text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_capability_shadow_events_user_exercise_time
  on public.capability_shadow_events(user_id,exercise_id,created_at desc);
create index if not exists idx_capability_shadow_events_session
  on public.capability_shadow_events(session_id);
create index if not exists idx_capability_shadow_errors_session
  on public.capability_shadow_run_errors(session_id,created_at desc);

alter table public.user_exercise_capabilities_shadow enable row level security;
alter table public.capability_shadow_events enable row level security;
alter table public.capability_shadow_run_errors enable row level security;

drop policy if exists "Users can read own capability shadow state" on public.user_exercise_capabilities_shadow;
create policy "Users can read own capability shadow state"
  on public.user_exercise_capabilities_shadow
  for select to authenticated
  using (auth.uid()=user_id);

drop policy if exists "Users can read own capability shadow events" on public.capability_shadow_events;
create policy "Users can read own capability shadow events"
  on public.capability_shadow_events
  for select to authenticated
  using (auth.uid()=user_id);

drop policy if exists "Users can read own capability shadow errors" on public.capability_shadow_run_errors;
create policy "Users can read own capability shadow errors"
  on public.capability_shadow_run_errors
  for select to authenticated
  using (auth.uid()=user_id);

grant select on public.user_exercise_capabilities_shadow to authenticated;
grant select on public.capability_shadow_events to authenticated;
grant select on public.capability_shadow_run_errors to authenticated;

create or replace function public.resolve_exercise_log_instance()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  v_session_user uuid;
  v_match_count int;
  v_match_id uuid;
begin
  if new.session_id is null then
    return new;
  end if;

  select user_id into v_session_user
  from public.workout_sessions
  where id=new.session_id;

  if not found then
    raise exception 'Unknown workout session %',new.session_id;
  end if;

  if new.user_id<>v_session_user then
    raise exception 'exercise_logs user_id does not own session %',new.session_id;
  end if;

  if new.session_exercise_id is not null then
    if not exists(
      select 1 from public.workout_session_exercises wse
      where wse.id=new.session_exercise_id
        and wse.session_id=new.session_id
        and wse.exercise_id=new.exercise_id
    ) then
      raise exception 'session_exercise_id % does not match session/exercise',new.session_exercise_id;
    end if;
    return new;
  end if;

  select count(*),min(id)
  into v_match_count,v_match_id
  from public.workout_session_exercises
  where session_id=new.session_id
    and exercise_id=new.exercise_id;

  if v_match_count=1 then
    new.session_exercise_id:=v_match_id;
  elsif v_match_count=0 then
    if coalesce(new.source_kind,'internal')='internal' then
      raise exception 'No workout_session_exercise instance for session %, exercise %',new.session_id,new.exercise_id;
    end if;
  else
    raise exception 'Ambiguous exercise instance for session %, exercise %. Pass session_exercise_id explicitly.',new.session_id,new.exercise_id;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_resolve_exercise_log_instance on public.exercise_logs;
create trigger trg_resolve_exercise_log_instance
before insert or update of session_id,exercise_id,session_exercise_id
on public.exercise_logs
for each row
execute function public.resolve_exercise_log_instance();

create or replace function public.run_capability_shadow_session(
  p_session_id uuid,
  p_engine_policy_key text default 'b2.5-draft-default',
  p_quality_policy_key text default 'b2.6-adapter-draft-1'
) returns jsonb
language plpgsql
volatile
security definer
set search_path=public
as $$
declare
  v_user_id uuid;
  v_log record;
  v_state jsonb;
  v_adapter jsonb;
  v_update jsonb;
  v_result jsonb;
  v_processed int:=0;
  v_skipped_existing int:=0;
  v_mode text;
  v_family text;
  v_reason text[];
begin
  select user_id into v_user_id
  from public.workout_sessions
  where id=p_session_id;

  if not found then
    raise exception 'Unknown session %',p_session_id;
  end if;

  if auth.uid() is not null and auth.uid()<>v_user_id then
    raise exception 'Cannot run shadow for another user session';
  end if;

  for v_log in
    select id,user_id,exercise_id,session_exercise_id,created_at
    from public.exercise_logs
    where session_id=p_session_id
    order by created_at,id
  loop
    select state_json into v_state
    from public.user_exercise_capabilities_shadow
    where user_id=v_log.user_id and exercise_id=v_log.exercise_id
    for update;

    if not found then
      v_state:=public.capability_state_snapshot(v_log.user_id,v_log.exercise_id::varchar);
    end if;

    v_adapter:=public.build_capability_observation_inputs(v_log.id,p_quality_policy_key);

    for v_update in
      select value from jsonb_array_elements(coalesce(v_adapter->'updates','[]'::jsonb))
    loop
      v_family:=v_update->>'family';
      v_mode:=v_update->>'capability_mode';

      if exists(
        select 1 from public.capability_shadow_events
        where exercise_log_id=v_log.id
          and capability_family=v_family
          and capability_mode=v_mode
      ) then
        v_skipped_existing:=v_skipped_existing+1;
        continue;
      end if;

      v_result:=public.propose_capability_state_update(
        v_state,
        v_family,
        coalesce(v_adapter->'expected','{}'::jsonb),
        coalesce(v_adapter->'actual','{}'::jsonb),
        coalesce((v_update->>'quality')::numeric,0),
        coalesce((v_adapter->>'capability_eligible')::boolean,false),
        coalesce((v_adapter->>'pain_affected')::boolean,false),
        coalesce(v_update->'comparison','{}'::jsonb),
        p_engine_policy_key,
        coalesce(v_log.created_at,now())
      );

      v_state:=coalesce(v_result->'after_state',v_state);

      select coalesce(array_agg(x),'{}'::text[])
      into v_reason
      from jsonb_array_elements_text(coalesce(v_result->'proposal'->'reason_codes','[]'::jsonb)) x;

      insert into public.capability_shadow_events(
        user_id,session_id,exercise_log_id,session_exercise_id,exercise_id,
        capability_family,capability_mode,decision,signal,confirmed_now,
        quality,effective_evidence,confidence,reason_codes,comparison_json,result_json
      ) values (
        v_log.user_id,p_session_id,v_log.id,v_log.session_exercise_id,v_log.exercise_id,
        v_family,v_mode,coalesce(v_result->>'decision','HOLD'),coalesce(v_result->>'signal','NONE'),
        coalesce((v_result->>'confirmed_now')::boolean,false),coalesce((v_update->>'quality')::numeric,0),
        nullif(v_result->>'effective_evidence','')::numeric,
        nullif(v_result->>'confidence','')::numeric,
        v_reason,coalesce(v_update->'comparison','{}'::jsonb),v_result
      );

      v_processed:=v_processed+1;
    end loop;

    insert into public.user_exercise_capabilities_shadow(
      user_id,exercise_id,state_json,engine_policy_key,quality_policy_key,last_observed_at,updated_at
    ) values (
      v_log.user_id,v_log.exercise_id,v_state,p_engine_policy_key,p_quality_policy_key,v_log.created_at,now()
    )
    on conflict(user_id,exercise_id) do update set
      state_json=excluded.state_json,
      engine_policy_key=excluded.engine_policy_key,
      quality_policy_key=excluded.quality_policy_key,
      last_observed_at=greatest(public.user_exercise_capabilities_shadow.last_observed_at,excluded.last_observed_at),
      updated_at=now();
  end loop;

  return jsonb_build_object(
    'shadow_version','b2.6.3-runtime-1',
    'session_id',p_session_id,
    'user_id',v_user_id,
    'processed_proposals',v_processed,
    'skipped_existing_proposals',v_skipped_existing,
    'real_capability_mutated',false
  );
end;
$$;

revoke all on function public.run_capability_shadow_session(uuid,text,text) from public;
grant execute on function public.run_capability_shadow_session(uuid,text,text) to authenticated;

create or replace function public.capability_shadow_on_session_complete()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if new.status='completed' and old.status is distinct from 'completed' then
    begin
      perform public.run_capability_shadow_session(new.id);
    exception when others then
      insert into public.capability_shadow_run_errors(user_id,session_id,error_text)
      values(new.user_id,new.id,sqlerrm);
    end;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_capability_shadow_on_session_complete on public.workout_sessions;
create trigger trg_capability_shadow_on_session_complete
after update of status on public.workout_sessions
for each row
execute function public.capability_shadow_on_session_complete();

comment on table public.user_exercise_capabilities_shadow is
'B2.6.3 isolated shadow state. Never consumed by the production session engine and never writes user_exercise_capabilities.';
comment on table public.capability_shadow_events is
'B2.6.3 shadow decisions generated from completed sessions for comparison/stress testing only.';
comment on function public.run_capability_shadow_session(uuid,text,text) is
'Runs B2.5 capability proposals against isolated shadow state. Does not mutate real user capabilities.';;
