create table public.skill_prerequisite_edges (
  id bigint generated by default as identity primary key,
  path_key text not null references public.skill_paths(path_key) on delete cascade,
  target_exercise_id varchar not null references public.exercises(id) on delete cascade,
  prerequisite_kind text not null check (prerequisite_kind in ('SKILL_STEP','EXERCISE_CAPABILITY','EQUIPMENT_ACCESS','ATHLETIC_DIMENSION')),
  prerequisite_exercise_id varchar references public.exercises(id) on delete cascade,
  requirement_json jsonb not null default '{}'::jsonb,
  source text not null,
  confidence numeric not null default 1.0 check (confidence>=0 and confidence<=1),
  rationale text,
  version text not null default 'w3-skill-prerequisite-v1',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (prerequisite_kind<>'SKILL_STEP' or prerequisite_exercise_id is not null)
);

create unique index skill_prerequisite_edges_step_uq
on public.skill_prerequisite_edges(path_key,target_exercise_id,prerequisite_kind,prerequisite_exercise_id,source)
where prerequisite_exercise_id is not null;

create index skill_prerequisite_edges_target_idx
on public.skill_prerequisite_edges(path_key,target_exercise_id)
where active;

alter table public.skill_prerequisite_edges enable row level security;
create policy skill_prerequisite_edges_read on public.skill_prerequisite_edges
for select to authenticated using (true);
revoke all on public.skill_prerequisite_edges from anon;
grant select on public.skill_prerequisite_edges to authenticated,service_role;

with candidates as (
  select
    m.path_key,
    m.exercise_id as target_exercise_id,
    m.step_order as target_step,
    m.member_role as target_role,
    p.exercise_id as prerequisite_exercise_id,
    p.step_order as prerequisite_step,
    row_number() over (
      partition by m.path_key,m.exercise_id
      order by p.step_order desc,p.exercise_id
    ) as rn,
    count(*) over (
      partition by m.path_key,m.exercise_id,p.step_order
    ) as candidates_at_selected_step
  from public.skill_path_members m
  join public.skill_path_members p
    on p.path_key=m.path_key
   and p.active
   and p.step_order<m.step_order
   and (
     (m.member_role='main' and p.member_role in ('entry','main'))
     or (
       m.member_role not in ('entry','main','alternate')
       and p.member_role=m.member_role
     )
   )
  where m.active
    and m.member_role<>'alternate'
), safe as (
  select *
  from candidates
  where rn=1 and candidates_at_selected_step=1
)
insert into public.skill_prerequisite_edges(
  path_key,target_exercise_id,prerequisite_kind,prerequisite_exercise_id,
  source,confidence,rationale,version
)
select
  path_key,target_exercise_id,'SKILL_STEP',prerequisite_exercise_id,
  'DERIVED_FROM_CURATED_PATH_ORDER_V1',1.0,
  'Structural predecessor derived only from the existing curated path order and same compatible branch role; this is not a physiological causal claim.',
  'w3-skill-prerequisite-v1'
from safe
on conflict do nothing;

create or replace function public.w3_skill_prerequisite_graph_v1(
  p_path_key text default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path=public
as $$
declare
  v_paths jsonb:='[]'::jsonb;
  v_path_count int:=0;
  v_member_count int:=0;
  v_edge_count int:=0;
  v_uncovered_non_entry int:=0;
begin
  if p_path_key is not null and not exists(
    select 1 from public.skill_paths where path_key=p_path_key and active
  ) then
    raise exception 'Unknown active skill path';
  end if;

  with members as (
    select sp.path_key,sp.display_name,sp.body_region,sp.selection_priority,
           m.exercise_id,m.step_order,m.member_role,
           coalesce(nullif(e.display_name,''),e.name) exercise_name,
           coalesce((
             select jsonb_agg(jsonb_strip_nulls(jsonb_build_object(
               'edge_id',pe.id,
               'kind',pe.prerequisite_kind,
               'prerequisite_exercise_id',pe.prerequisite_exercise_id,
               'prerequisite_exercise_name',coalesce(nullif(pre.display_name,''),pre.name),
               'requirement',pe.requirement_json,
               'source',pe.source,
               'confidence',pe.confidence,
               'rationale',pe.rationale,
               'version',pe.version
             )) order by pe.id)
             from public.skill_prerequisite_edges pe
             left join public.exercises pre on pre.id=pe.prerequisite_exercise_id
             where pe.path_key=sp.path_key
               and pe.target_exercise_id=m.exercise_id
               and pe.active
           ),'[]'::jsonb) prerequisites
    from public.skill_paths sp
    join public.skill_path_members m on m.path_key=sp.path_key and m.active
    join public.exercises e on e.id=m.exercise_id
    where sp.active
      and (p_path_key is null or sp.path_key=p_path_key)
  ), path_objects as (
    select
      path_key,
      max(display_name) path_name,
      max(body_region) body_region,
      max(selection_priority) selection_priority,
      jsonb_agg(jsonb_build_object(
        'exercise_id',exercise_id,
        'exercise_name',exercise_name,
        'step_order',step_order,
        'member_role',member_role,
        'prerequisites',prerequisites,
        'prerequisite_coverage',case
          when member_role='entry' then 'ENTRY_NO_PREREQUISITE_REQUIRED'
          when member_role='alternate' then 'BRANCH_RELATION_NOT_INFERRED'
          when jsonb_array_length(prerequisites)>0 then 'COVERED'
          else 'MODEL_INCOMPLETE'
        end
      ) order by step_order,member_role,exercise_id) members
    from members
    group by path_key
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'path_key',path_key,
    'path_name',path_name,
    'body_region',body_region,
    'selection_priority',selection_priority,
    'members',members
  ) order by selection_priority desc,path_key),'[]'::jsonb),count(*)::int
  into v_paths,v_path_count
  from path_objects;

  select count(*)::int into v_member_count
  from public.skill_path_members m
  join public.skill_paths sp on sp.path_key=m.path_key
  where m.active and sp.active and (p_path_key is null or m.path_key=p_path_key);

  select count(*)::int into v_edge_count
  from public.skill_prerequisite_edges pe
  where pe.active and (p_path_key is null or pe.path_key=p_path_key);

  select count(*)::int into v_uncovered_non_entry
  from public.skill_path_members m
  join public.skill_paths sp on sp.path_key=m.path_key and sp.active
  where m.active
    and m.member_role not in ('entry','alternate')
    and (p_path_key is null or m.path_key=p_path_key)
    and not exists(
      select 1 from public.skill_prerequisite_edges pe
      where pe.path_key=m.path_key and pe.target_exercise_id=m.exercise_id and pe.active
    );

  return jsonb_build_object(
    'version','w3-skill-prerequisite-graph-v1',
    'summary',jsonb_build_object(
      'paths',v_path_count,
      'members',v_member_count,
      'active_edges',v_edge_count,
      'uncovered_non_entry_members',v_uncovered_non_entry
    ),
    'paths',v_paths,
    'semantics',jsonb_build_object(
      'graph_is_versioned',true,
      'structural_order_is_not_a_physiological_causal_claim',true,
      'ambiguous_branch_edges_are_not_inferred',true,
      'missing_edge_is_model_incomplete_not_athlete_weakness',true,
      'additional_exercise_equipment_or_athletic_prerequisites_require_explicit_curation',true
    )
  );
end;
$$;

revoke all on function public.w3_skill_prerequisite_graph_v1(text) from public,anon;
grant execute on function public.w3_skill_prerequisite_graph_v1(text) to authenticated,service_role;

comment on table public.skill_prerequisite_edges is 'W3 SKL-001 versioned prerequisite graph. Initial rows encode only structurally safe predecessor relations derived from curated Skill paths; no physiological prerequisite is invented.';
